[package]
name = "redizone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redcon = "0.1.2"
tzf-rs = "0.4.1"
