name: build

on:
  push:
    tags:
      - "*"

jobs:
  build-image:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # permissions:
    #   packages: write
    #   contents: read
    env:
      IMAGE_REGISTRY: "ghcr.io"
      IMAGE_OWNER: "ringsaturn"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate short SHA
        uses: benjlevesque/short-sha@v2.2
        id: gen-short-sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: false
